

export const baseTextColorClasses = {
    slate: 'text-slate-600',
    gray: 'text-gray-600',
    zinc: 'text-zinc-600',
    neutral: 'text-neutral-600',
    stone: 'text-stone-600',
    red: 'text-red-600',
    orange: 'text-orange-600',
    amber: 'text-amber-600',
    yellow: 'text-yellow-600',
    lime: 'text-lime-600',
    green: 'text-green-600',
    emerald: 'text-emerald-600',
    teal: 'text-teal-600',
    cyan: 'text-cyan-600',
    sky: 'text-sky-600',
    blue: 'text-blue-600',
    indigo: 'text-indigo-600',
    violet: 'text-violet-600',
    purple: 'text-purple-600',
    fuchsia: 'text-fuchsia-600',
    pink: 'text-pink-600',
    rose: 'text-rose-600',
};

export const baseBgColorClasses = {
    slate: 'bg-slate-600',
    gray: 'bg-gray-600',
    zinc: 'bg-zinc-600',
    neutral: 'bg-neutral-600',
    stone: 'bg-stone-600',
    red: 'bg-red-600',
    orange: 'bg-orange-600',
    amber: 'bg-amber-600',
    yellow: 'bg-yellow-600',
    lime: 'bg-lime-600',
    green: 'bg-green-600',
    emerald: 'bg-emerald-600',
    teal: 'bg-teal-600',
    cyan: 'bg-cyan-600',
    sky: 'bg-sky-600',
    blue: 'bg-blue-600',
    indigo: 'bg-indigo-600',
    violet: 'bg-violet-600',
    purple: 'bg-purple-600',
    fuchsia: 'bg-fuchsia-600',
    pink: 'bg-pink-600',
    rose: 'bg-rose-600',
};

export const softBaseBgColorClasses = {
    slate: 'bg-slate-50',
    gray: 'bg-gray-50',
    zinc: 'bg-zinc-50',
    neutral: 'bg-neutral-50',
    stone: 'bg-stone-50',
    red: 'bg-red-50',
    orange: 'bg-orange-50',
    amber: 'bg-amber-50',
    yellow: 'bg-yellow-50',
    lime: 'bg-lime-50',
    green: 'bg-green-50',
    emerald: 'bg-emerald-50',
    teal: 'bg-teal-50',
    cyan: 'bg-cyan-50',
    sky: 'bg-sky-50',
    blue: 'bg-blue-50',
    indigo: 'bg-indigo-50',
    violet: 'bg-violet-50',
    purple: 'bg-purple-50',
    fuchsia: 'bg-fuchsia-50',
    pink: 'bg-pink-50',
    rose: 'bg-rose-50',
};

export const hoverBgColorClasses = {
    slate: 'hover:bg-slate-500',
    gray: 'hover:bg-gray-500',
    zinc: 'hover:bg-zinc-500',
    neutral: 'hover:bg-neutral-500',
    stone: 'hover:bg-stone-500',
    red: 'hover:bg-red-500',
    orange: 'hover:bg-orange-500',
    amber: 'hover:bg-amber-500',
    yellow: 'hover:bg-yellow-500',
    lime: 'hover:bg-lime-500',
    green: 'hover:bg-green-500',
    emerald: 'hover:bg-emerald-500',
    teal: 'hover:bg-teal-500',
    cyan: 'hover:bg-cyan-500',
    sky: 'hover:bg-sky-500',
    blue: 'hover:bg-blue-500',
    indigo: 'hover:bg-indigo-500',
    violet: 'hover:bg-violet-500',
    purple: 'hover:bg-purple-500',
    fuchsia: 'hover:bg-fuchsia-500',
    pink: 'hover:bg-pink-500',
    rose: 'hover:bg-rose-500',
};

export const softHoverBgColorClasses = {
    slate: 'hover:bg-slate-100',
    gray: 'hover:bg-gray-100',
    zinc: 'hover:bg-zinc-100',
    neutral: 'hover:bg-neutral-100',
    stone: 'hover:bg-stone-100',
    red: 'hover:bg-red-100',
    orange: 'hover:bg-orange-100',
    amber: 'hover:bg-amber-100',
    yellow: 'hover:bg-yellow-100',
    lime: 'hover:bg-lime-100',
    green: 'hover:bg-green-100',
    emerald: 'hover:bg-emerald-100',
    teal: 'hover:bg-teal-100',
    cyan: 'hover:bg-cyan-100',
    sky: 'hover:bg-sky-100',
    blue: 'hover:bg-blue-100',
    indigo: 'hover:bg-indigo-100',
    violet: 'hover:bg-violet-100',
    purple: 'hover:bg-purple-100',
    fuchsia: 'hover:bg-fuchsia-100',
    pink: 'hover:bg-pink-100',
    rose: 'hover:bg-rose-100',
};

export const darkBgColorClasses = {
    slate: 'dark:bg-slate-500',
    gray: 'dark:bg-gray-500',
    zinc: 'dark:bg-zinc-500',
    neutral: 'dark:bg-neutral-500',
    stone: 'dark:bg-stone-500',
    red: 'dark:bg-red-500',
    orange: 'dark:bg-orange-500',
    amber: 'dark:bg-amber-500',
    yellow: 'dark:bg-yellow-500',
    lime: 'dark:bg-lime-500',
    green: 'dark:bg-green-500',
    emerald: 'dark:bg-emerald-500',
    teal: 'dark:bg-teal-500',
    cyan: 'dark:bg-cyan-500',
    sky: 'dark:bg-sky-500',
    blue: 'dark:bg-blue-500',
    indigo: 'dark:bg-indigo-500',
    violet: 'dark:bg-violet-500',
    purple: 'dark:bg-purple-500',
    fuchsia: 'dark:bg-fuchsia-500',
    pink: 'dark:bg-pink-500',
    rose: 'dark:bg-rose-500',
};

export const darkHoverBgColorClasses = {
    slate: 'dark:hover:bg-slate-400',
    gray: 'dark:hover:bg-gray-400',
    zinc: 'dark:hover:bg-zinc-400',
    neutral: 'dark:hover:bg-neutral-400',
    stone: 'dark:hover:bg-stone-400',
    red: 'dark:hover:bg-red-400',
    orange: 'dark:hover:bg-orange-400',
    amber: 'dark:hover:bg-amber-400',
    yellow: 'dark:hover:bg-yellow-400',
    lime: 'dark:hover:bg-lime-400',
    green: 'dark:hover:bg-green-400',
    emerald: 'dark:hover:bg-emerald-400',
    teal: 'dark:hover:bg-teal-400',
    cyan: 'dark:hover:bg-cyan-400',
    sky: 'dark:hover:bg-sky-400',
    blue: 'dark:hover:bg-blue-400',
    indigo: 'dark:hover:bg-indigo-400',
    violet: 'dark:hover:bg-violet-400',
    purple: 'dark:hover:bg-purple-400',
    fuchsia: 'dark:hover:bg-fuchsia-400',
    pink: 'dark:hover:bg-pink-400',
    rose: 'dark:hover:bg-rose-400',
};

export const focusOutlineClasses = {
    slate: 'focus-visible:outline-slate-600',
    gray: 'focus-visible:outline-gray-600',
    zinc: 'focus-visible:outline-zinc-600',
    neutral: 'focus-visible:outline-neutral-600',
    stone: 'focus-visible:outline-stone-600',
    red: 'focus-visible:outline-red-600',
    orange: 'focus-visible:outline-orange-600',
    amber: 'focus-visible:outline-amber-600',
    yellow: 'focus-visible:outline-yellow-600',
    lime: 'focus-visible:outline-lime-600',
    green: 'focus-visible:outline-green-600',
    emerald: 'focus-visible:outline-emerald-600',
    teal: 'focus-visible:outline-teal-600',
    cyan: 'focus-visible:outline-cyan-600',
    sky: 'focus-visible:outline-sky-600',
    blue: 'focus-visible:outline-blue-600',
    indigo: 'focus-visible:outline-indigo-600',
    violet: 'focus-visible:outline-violet-600',
    purple: 'focus-visible:outline-purple-600',
    fuchsia: 'focus-visible:outline-fuchsia-600',
    pink: 'focus-visible:outline-pink-600',
    rose: 'focus-visible:outline-rose-600',
};

export const darkFocusOutlineClasses = {
    slate: 'dark:focus-visible:outline-slate-500',
    gray: 'dark:focus-visible:outline-gray-500',
    zinc: 'dark:focus-visible:outline-zinc-500',
    neutral: 'dark:focus-visible:outline-neutral-500',
    stone: 'dark:focus-visible:outline-stone-500',
    red: 'dark:focus-visible:outline-red-500',
    orange: 'dark:focus-visible:outline-orange-500',
    amber: 'dark:focus-visible:outline-amber-500',
    yellow: 'dark:focus-visible:outline-yellow-500',
    lime: 'dark:focus-visible:outline-lime-500',
    green: 'dark:focus-visible:outline-green-500',
    emerald: 'dark:focus-visible:outline-emerald-500',
    teal: 'dark:focus-visible:outline-teal-500',
    cyan: 'dark:focus-visible:outline-cyan-500',
    sky: 'dark:focus-visible:outline-sky-500',
    blue: 'dark:focus-visible:outline-blue-500',
    indigo: 'dark:focus-visible:outline-indigo-500',
    violet: 'dark:focus-visible:outline-violet-500',
    purple: 'dark:focus-visible:outline-purple-500',
    fuchsia: 'dark:focus-visible:outline-fuchsia-500',
    pink: 'dark:focus-visible:outline-pink-500',
    rose: 'dark:focus-visible:outline-rose-500',
};